title: AMOF Game Engine
description: A game engine based on AdvancedMogreFramework including Network, Physx, AI and so on.
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
